scan_table_dynamic = {
"CharacterDead":{"Toggle":"True",
                "ImgName":"dead.png",
                "Threshold":"0",
                "Invert":"False",
                "flag":"character_dead"},
"CursedRune":{"Toggle":"True",
                "ImgName":"cursedRune.png",
                "Threshold":"0",
                "Invert":"False",
                "flag":"cursed_rune"},
"ViolettaLieDetector":{"Toggle":"True",
                "ImgName":"LD.png", 
                "Threshold":"0",
                "Invert":"False",
                "flag":"violetta_minigame"},     
"LieDetectorFailed":{"Toggle":"True",
                "ImgName":"LDwarning.png",
                "Threshold":"0",
                "Invert":"False",
                "flag":"lie_detector_failed"},         
"NoDamageNumbers":{"Toggle":"True",
                "ImgName":"ds.png",
                "Threshold":"8",
                "Invert":"True",
                "flag":"no_damage_numbers"},
"StuckInCS":{"Toggle":"True",
                "ImgName":"insidecashshop.png",
                "Threshold":"5",
                "Invert":"False",
                "flag":"stuck_in_cs"},
"EspeciaPortal":{"Toggle":"True",
                "ImgName":"especiaPortal.png",
                "Threshold":"0",
                "Invert":"False",
                "flag":"especia_portal"}
}

scan_table_static = {
"MaplestoryDC":{"Toggle":"True",
                "ImgName1":"dced.png",
                "ImgName2":"dced2.png",
                "ImgName3":"dced3.png",
                "ImgName4":"dced3.png",
                "flag":"game_disconnected"},
"ChatDetection":{"Toggle":"True",
                "ImgName":"exp.png",
                "flag":"CRITICAL: Chat detected @everyone",
                "ChatboxMissingMsg":"STATUS: Chat window not visible @everyone"},
"MushBuff":{"Toggle":"True",
                "ImgName1":"mushbuff.png",
                "ImgName2":"mushbuff2.png",
                "flag":"STATUS: EXP Buff Ended"},
"CharacterStationary":{"Toggle":"True",
                "ImgName":"char.png",
                "Threshold":"15",
                "flag":"STATUS: Character not moving @everyone"}
}